/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlquannet.gui;

import com.qlquannet.helper.dialogHelper;
import com.qlquannet.helper.shareHelper;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author nana
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        init();
    }

    void init() {
        setIconImage(shareHelper.APP_ICON); //đặt icon góc trên trái
        setLocationRelativeTo(null);    //cho ra giữa màn hình
        setExtendedState(JFrame.MAXIMIZED_BOTH);    //cho toàn màn hình 
        /*
        làm đồng hồ
        Timer t=new Timer(s, ActionListener); sk lặp lại sau s ms
        t.start() / t.stop()
         */
        new Timer(1000, new ActionListener() {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss ");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(sdf.format(new Date()));
            }
        }).start();
        
    }

    
    
    void exit() {
        if (dialogHelper.confirm(this, "Bạn thực sự muốn kết thúc?")) {
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        jdesktop = new javax.swing.JDesktopPane(){
            protected void  paintComponent (Graphics g){
                Image img = new ImageIcon(this.getClass().getResource("/com/qlquannet/icons/bg.jpg")).getImage();
                try {
                    Graphics g2d = (Graphics2D)g;
                    double x= img.getWidth(null);
                    double y= img.getHeight(null);
                    //g2d.scale(getWidth()/x,getHeight()/y);
                    //g2d.drawImage(img, 0, 0, this);
                    g2d.drawImage(img, this.getWidth(),this.getHeight(),this);
                } catch (Exception e) {
                    System.out.println("Gap loi");
                }
            }}
            ;
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            mniLogin = new javax.swing.JMenuItem();
            mniLogOut = new javax.swing.JMenuItem();
            jSeparator1 = new javax.swing.JPopupMenu.Separator();
            mniDoiPass = new javax.swing.JMenuItem();
            jSeparator2 = new javax.swing.JPopupMenu.Separator();
            mniKetThuc = new javax.swing.JMenuItem();
            jMenu6 = new javax.swing.JMenu();
            jMenuItem13 = new javax.swing.JMenuItem();
            jSeparator5 = new javax.swing.JPopupMenu.Separator();
            jMenuItem14 = new javax.swing.JMenuItem();
            jMenu2 = new javax.swing.JMenu();
            jMenuItem5 = new javax.swing.JMenuItem();
            jMenuItem6 = new javax.swing.JMenuItem();
            jMenuItem7 = new javax.swing.JMenuItem();
            jMenuItem1 = new javax.swing.JMenuItem();
            jMenu4 = new javax.swing.JMenu();
            mniTKeNguoiHoc = new javax.swing.JMenuItem();
            jSeparator3 = new javax.swing.JPopupMenu.Separator();
            mniBangDiem = new javax.swing.JMenuItem();
            jSeparator4 = new javax.swing.JPopupMenu.Separator();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(153, 153, 255));

            jToolBar1.setRollover(true);

            jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlquannet/icons/Log out.png"))); // NOI18N
            jButton1.setText("Đăng xuất");
            jButton1.setFocusable(false);
            jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jButton1.setMargin(new java.awt.Insets(12, 30, 12, 30));
            jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jToolBar1.add(jButton1);

            jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlquannet/icons/Stop.png"))); // NOI18N
            jButton2.setText("Thoát");
            jButton2.setFocusable(false);
            jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jButton2.setMargin(new java.awt.Insets(12, 30, 12, 30));
            jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jToolBar1.add(jButton2);
            jToolBar1.add(jSeparator6);

            jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlquannet/icons/Desktop.png"))); // NOI18N
            jButton4.setText("Máy");
            jButton4.setFocusable(false);
            jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jButton4.setMargin(new java.awt.Insets(12, 30, 12, 30));
            jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jToolBar1.add(jButton4);

            jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlquannet/icons/Bricks.png"))); // NOI18N
            jButton5.setText("Dịch vụ");
            jButton5.setFocusable(false);
            jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jButton5.setMargin(new java.awt.Insets(12, 30, 12, 30));
            jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jToolBar1.add(jButton5);

            jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlquannet/icons/Dollar.png"))); // NOI18N
            jButton6.setText("Doanh thu");
            jButton6.setFocusable(false);
            jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jButton6.setMargin(new java.awt.Insets(12, 30, 12, 30));
            jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jToolBar1.add(jButton6);

            lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            lblDongHo.setForeground(new java.awt.Color(102, 0, 51));
            lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlquannet/icons/Alarm.png"))); // NOI18N
            lblDongHo.setText("12:00");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(432, Short.MAX_VALUE)
                    .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(126, 126, 126))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lblDongHo)
                    .addGap(0, 6, Short.MAX_VALUE))
            );

            jdesktop.setBackground(new java.awt.Color(157, 189, 228));
            getContentPane().add(jdesktop, java.awt.BorderLayout.CENTER);

            javax.swing.GroupLayout jdesktopLayout = new javax.swing.GroupLayout(jdesktop);
            jdesktop.setLayout(jdesktopLayout);
            jdesktopLayout.setHorizontalGroup(
                jdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 666, Short.MAX_VALUE)
            );
            jdesktopLayout.setVerticalGroup(
                jdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 296, Short.MAX_VALUE)
            );

            jMenu1.setText("Hệ thống");
            jMenu1.setMargin(new java.awt.Insets(5, 5, 5, 5));

            mniLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
            mniLogin.setText("Đăng nhập");
            mniLogin.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu1.add(mniLogin);

            mniLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
            mniLogOut.setText("Đăng xuất");
            mniLogOut.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu1.add(mniLogOut);
            jMenu1.add(jSeparator1);

            mniDoiPass.setText("Đổi mật khẩu");
            mniDoiPass.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu1.add(mniDoiPass);
            jMenu1.add(jSeparator2);

            mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
            mniKetThuc.setText("Kết thúc");
            mniKetThuc.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu1.add(mniKetThuc);

            jMenuBar1.add(jMenu1);

            jMenu6.setText("Nghiệp vụ");
            jMenu6.setMargin(new java.awt.Insets(5, 5, 5, 5));

            jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
            jMenuItem13.setText("Máy");
            jMenuItem13.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu6.add(jMenuItem13);
            jMenu6.add(jSeparator5);

            jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
            jMenuItem14.setText("Dịch vụ");
            jMenuItem14.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu6.add(jMenuItem14);

            jMenuBar1.add(jMenu6);

            jMenu2.setText("Quản lý");
            jMenu2.setMargin(new java.awt.Insets(5, 5, 5, 5));

            jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
            jMenuItem5.setText("Máy trạm");
            jMenuItem5.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu2.add(jMenuItem5);

            jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
            jMenuItem6.setText("Dịch vụ");
            jMenuItem6.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu2.add(jMenuItem6);

            jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
            jMenuItem7.setText("Nhân viên");
            jMenuItem7.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu2.add(jMenuItem7);

            jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
            jMenuItem1.setText("Khách hàng");
            jMenu2.add(jMenuItem1);

            jMenuBar1.add(jMenu2);

            jMenu4.setText("Thống kê");
            jMenu4.setMargin(new java.awt.Insets(5, 5, 5, 5));

            mniTKeNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
            mniTKeNguoiHoc.setText("Doanh thu");
            mniTKeNguoiHoc.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu4.add(mniTKeNguoiHoc);
            jMenu4.add(jSeparator3);

            mniBangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
            mniBangDiem.setText("Số lượng khách");
            mniBangDiem.setMargin(new java.awt.Insets(5, 5, 5, 5));
            jMenu4.add(mniBangDiem);
            jMenu4.add(jSeparator4);

            jMenuBar1.add(jMenu4);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jdesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jdesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdesktop;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniDoiPass;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniLogOut;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniTKeNguoiHoc;
    // End of variables declaration//GEN-END:variables
}
